### ISSUE TITLE
Activity and CCA Database

### ISSUE THREAD

**Issue by Niubiable1** [nyjc-computing-2324/meow-2024#107]
## Task

Backend Lead @ratSpoT to work on activity and CCA database
QA Lead @saathvik28 to check
Security Lead @TheLegendaryZHR to check

## Deliverables

Google Doc with list of concrete actions required. Inform tech lead.

Involved: @nyjc-computing-2324/frontend, @nyjc-computing-2324/backend

**Comment by TheLegendaryZHR** [comment]
Use **parameterised inputs** whenever possible. If f-strings must be used, make sure to properly validate the fields.

Example of validated f-string query:
https://github.com/nyjc-computing-2324/meow-2024/blob/d278ed010ffd631af35765277c00c41487b21414/database.py#L75-L83

Avoid making implicit **assumptions** about user behavior or the behavior of other parts of the application.
**Validate** as much as possible.
Write **clear documentation** and **state any assumptions** made about the inputs.
