### ISSUE TITLE
User Input Validation (For register and login pages)

### ISSUE THREAD

**Issue by Niubiable1** [nyjc-computing-2324/meow-2024#28]
## Task

Backend Lead @ratSpoT to implement validation
UI/UX Designer @TranHuyThai to design a standard display of messages
Frontend Lead @mc4706 to implement messages in Login and Register page

## Deliverables

Appropriate message for invalid/valid user input

Involved: @nyjc-computing-2324/backend , @nyjc-computing-2324/frontend

**Comment by ngjunsiang** [comment]
@awpgikxdigj to advise on appropriate format for exchange between frontend and backend
