### ISSUE TITLE
Setting up database

### ISSUE THREAD

**Issue by Niubiable1** [nyjc-computing-2324/meow-2024#29]
## Task

Backend Lead @ratSpoT to set up basic database, making sure data from register can be stored

Involved: @nyjc-computing-2324/backend

**Comment by ngjunsiang** [comment]
@TheLegendaryZHR please monitor and advise on best practices, inform of any potential vulnerabilities

**Comment by ngjunsiang** [comment]
@awpgikxdigj you probably want to keep close tabs on this. making db column names match the html input field names will go a long way in keeping the code manageable.

**Comment by ngjunsiang** [comment]
@kantanana + @TheLegendaryZHR you probably also want to monitor this to ensure the dev db doesn't get pushed to the repo. check with @ratSpoT what db he is using and update .gitignore accordingly.

**Comment by TheLegendaryZHR** [comment]
1. validate and sanitise user input
2. ensure that parameterised queries or prepared queries are used when storing the data in the database or in any interaction with the database
3. should implement salting and hashing for passwords
