### ISSUE TITLE
Landing page (skeleton)

### ISSUE THREAD

**Issue by Niubiable1** [nyjc-computing-2324/meow-2024#31]
## Task

Frontend Lead @mc4706 to implement skeleton of the landing page. 
Include routes to all other pages and title, with minimal design

## Deliverables

Home page with minimal design, working routes

Involved: @nyjc-computing-2324/frontend

**Comment by ngjunsiang** [comment]
Please clarify with @TranHuyThai if there are any ambiguities in layout
