### ISSUE TITLE
Login and Register Pages (skeleton)

### ISSUE THREAD

**Issue by Niubiable1** [nyjc-computing-2324/meow-2024#33]
## Task

Frontend Lead @mc4706 to implement login and register page
Login and Register functions should be working, user info stored in database

## Deliverables

Login and Register functions should be working, user info stored in database

Involved: @nyjc-computing-2324/frontend

**Comment by ngjunsiang** [comment]
(who's in charge of routing? @awpgikxdigj or @ratSpoT ? Tech lead please advise)

**Comment by ngjunsiang** [comment]
Routing IC (tech lead or backend lead) please provide frontend with the route(s) to use for login & register (since he shouldn't be touching backend)

@TheLegendaryZHR, @awpgikxdigj please advise on request method to use

**Comment by ngjunsiang** [comment]
Who needs to review this when done? @TranHuyThai for UX? @TheLegendaryZHR for security?

**Comment by awpgikxdigj** [comment]
routes and functions for login ("/login", "view.login()") and register ("/register", "view.register()") have been created in main.py and view.py respectively

for request methods i assume "get" and "post" are sufficient? i don't know about the security concerns though

**Comment by TheLegendaryZHR** [comment]
only get and post should be allowed

**Comment by ngjunsiang** [comment]
> routes and functions for login ("/login", "view.login()") and register ("/register", "view.register()") have been created in main.py and view.py respectively
> 
It's a good habit to also which branch they have been created in, since there are so many :)

**Comment by awpgikxdigj** [comment]
> > routes and functions for login ("/login", "view.login()") and register ("/register", "view.register()") have been created in main.py and view.py respectively
> 
> It's a good habit to also which branch they have been created in, since there are so many :)

they were created last sprint so they're in main, just remember to pull i guess
